name: CI/CD Demo

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout o código
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Rodar testes com feedback personalizado
      run: |
        echo "🧪 Iniciando testes automatizados..."
        pytest || (echo '❌ Testes falharam. Corrija antes de prosseguir com o deploy.' && exit 1)

    - name: Criar nova versão (simulado)
      run: echo "Versão publicada em $(date)" > release.txt

    - name: Commit da nova versão (release.txt)
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add release.txt
        git commit -m "Publica nova versão"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}